In [ ]:
Tensorflow Tutorial 


Tensorflow is one of the famous deep learning framework and library was designed by Google Team.
It was one of the free and open source software library in python language.That means it is very 
easy to develop deep learning projects on Tensorflow in an easy and efficient manner.


Tensorflow is mainly used in

1) Mathematical Operations
2) Linear Algebra
3) Concepts in Artificial Intelligence(AI)

In [ ]:
What is Tensorflow

Tensorflow is one of the popular library for both machine learning and deep learning and it is a free and open source 
library which was released on 9th november 2015 and developed by Google Brain Team. It is entirely based on python 
programming language and use for mathematical computation and data flow and it makes machine learning easier and faster.

Tensorflow can train and run the deep neural networks for image recognition, handwritten digit classification,
recurrent neural network, word embedding and natural language processing,video detection and many more.

Tensorflow can run on both multiple cpu or gpu and mobile operating system also.

Tensorflow is divided into two words. they are 'tensor' and 'flow'.

Tensor - it is an multi-dimensional array.
flow - Flow is used to define the flow of data in operation.

Hence Tensorflow means Flow of Data in operation used on multi-dimensional array.

In [ ]:
History of TensorFlow
Many years ago, deep learning started to exceed all other machine learning algorithms when giving extensive data.
Google has seen it could use these deep neural networks to upgrade its services:

1) Google search engine
2) Gmail
3) Photo
They build a framework called TensorFlow to permit researchers and developers to work together in an AI model. 
Once it approved and scaled, it allows lots of people to use it.

It was first released in 2015, while the first stable version was coming in 2017. It is an open- source platform under Apache Open Source License.
We can use it, modify it, and reorganize the revised version for free without paying anything to Google.

In [ ]:
Applications and uses of Tensorflow

1) Voice/Sound Recognition
2) Image Recognition
3) Video Detection
4) Text-Based Application
5) Time Series

In [ ]:
Features of Tensorflow

1) Responsive Construct
2) Flexible
3) Easily Trainable
4) Parallel Neural Network Training
5) Open Source
6) Large Community
7) Layered Components
8) Feature Columns
9) Event Logger
10) Vizualizer

In [ ]:
Installing of Tensorflow

In Pip(Package Installer Python) by

'pip install tensorflow'

In [ ]:
Advantages of Tensorflow

1) Graphs
2) Library Management
3) Debugging
4) Pipelining
5) Scalability

In [ ]:
Disadavantages of Tensorflow

1) No support for windows
2) Missing Symbolic Loops
3) Computational test
4) Benchmark Testing
5) No GPU support other than NIVIDIA and only one language support.

In [ ]:
Tensorflow Operations

Add, Subtract, Multiply, Divide, Square, Reshape

In [4]:
import tensorflow as tf
a=10
b=20
c=tf.add(a,b)
print(c)

tf.Tensor(30, shape=(), dtype=int32)


In [5]:
import tensorflow as tf
a=10
b=20
c=tf.subtract(a,b)
print(c)

tf.Tensor(-10, shape=(), dtype=int32)


In [6]:
import tensorflow as tf
a=10
b=20
c=tf.multiply(a,b)
print(c)

tf.Tensor(200, shape=(), dtype=int32)


In [7]:
import tensorflow as tf
a=10
b=20
c=tf.divide(a,b)
print(c)

tf.Tensor(0.5, shape=(), dtype=float64)


In [10]:
import tensorflow as tf
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([[9,8],[7,6],[5,4]])
c=tf.add(a,b)
print(c)

tf.Tensor(
[[10 10]
 [10 10]
 [10 10]], shape=(3, 2), dtype=int32)


In [11]:
import tensorflow as tf
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([[9,8],[7,6],[5,4]])
c=tf.subtract(a,b)
print(c)

tf.Tensor(
[[-8 -6]
 [-4 -2]
 [ 0  2]], shape=(3, 2), dtype=int32)


In [13]:
import tensorflow as tf
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([[9,8],[7,6],[5,4]])
c=tf.dot(a,b)
print(c)

AttributeError: module 'tensorflow' has no attribute 'dot'

In [ ]:
Instead of Dot We need to use linalg matmul for dot operator

In [15]:
import tensorflow as tf
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([[9,8],[7,6]])
c=tf.linalg.matmul(a,b)
print(c)

tf.Tensor(
[[23 20]
 [55 48]
 [87 76]], shape=(3, 2), dtype=int32)
